using Apps.Matecat.Constants;
using Blackbird.Applications.Sdk.Common.Dictionaries;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Apps.Matecat.DataSourceHandlers.EnumDataHandlers
{
    public class LanguageDataHandler : IStaticDataSourceHandler
    {
        public Dictionary<string, string> GetData() => new()
        {
            {"ace-ID", "Acehnese"},
            {"af-ZA", "Afrikaans"},
            {"ak-GH", "Akan"},
            {"sq-AL", "Albanian"},
            {"am-ET", "Amharic"},
            {"aig-AG", "Antigua and Barbuda Creole English"},
            {"ar-SA", "Arabic"},
            {"ar-EG", "Arabic (Egypt)"},
            {"ar-JO", "Arabic (Jordan)"},
            {"ar-MA", "Arabic (Morocco)"},
            {"an-ES", "Aragonese"},
            {"hy-AM", "Armenian"},
            {"as-IN", "Assamese"},
            {"ast-ES", "Asturian"},
            {"awa-IN", "Awadhi"},
            {"quy-PE", "Ayacucho Quechua"},
            {"az-AZ", "Azerbaijani"},
            {"bah-BS", "Bahamas Creole English"},
            {"bjs-BB", "Bajan"},
            {"ban-ID", "Balinese"},
            {"rmn-BG", "Balkan Romani"},
            {"bm-ML", "Bambara"},
            {"bjn-ID", "Banjar"},
            {"ba-RU", "Bashkir"},
            {"eu-ES", "Basque"},
            {"be-BY", "Belarusian"},
            {"bem-ZM", "Bemba"},
            {"bn-BD", "Bengali (Bangladesh)"},
            {"bn-IN", "Bengali (India)"},
            {"bho-IN", "Bhojpuri"},
            {"bh-IN", "Bihari"},
            {"bi-VU", "Bislama"},
            {"gax-KE", "Borana"},
            {"bs-Cyrl-BA", "Bosnian (Cyrillic script)"},
            {"bs-BA", "Bosnian (Latin script)"},
            {"br-FR", "Breton"},
            {"bug-ID", "Buginese"},
            {"bg-BG", "Bulgarian"},
            {"my-MM", "Burmese"},
            {"ca-ES", "Catalan (Catalonia)"},
            {"cav-ES", "Catalan (Valencia)"},
            {"ceb-PH", "Cebuano"},
            {"tzm-MA", "Central Atlas Tamazight"},
            {"ayr-BO", "Central Aymara"},
            {"knc-NG", "Central Kanuri (Latin script)"},
            {"shu-TD", "Chadian Arabic"},
            {"ch-GU", "Chamorro"},
            {"chr-US", "Cherokee"},
            {"hne-IN", "Chhattisgarhi"},
            {"zh-CN", "Chinese (Simplified)"},
            {"zh-HK", "Chinese (Traditional, Hong Kong)"},
            {"zh-MO", "Chinese (Traditional, Macao)"},
            {"zh-TW", "Chinese (Traditional, Taiwan)"},
            {"ctg-BD", "Chittagonian"},
            {"cjk-AO", "Chokwe"},
            {"cac-GT", "Chuj"},
            {"grc-GR", "Classical Greek"},
            {"zdj-KM", "Comorian Ngazidja"},
            {"cop-EG", "Coptic"},
            {"crh-RU", "Crimean Tatar"},
            {"pov-GW", "Crioulo Upper Guinea"},
            {"hr-HR", "Croatian"},
            {"cs-CZ", "Czech"},
            {"da-DK", "Danish"},
            {"prs-AF", "Dari"},
            {"diq-TR", "Dimli"},
            {"nl-BE", "Dutch (Belgium)"},
            {"nl-NL", "Dutch (Netherlands)"},
            {"dyu-CI", "Dyula"},
            {"dz-BT", "Dzongkha"},
            {"ydd-US", "Eastern Yiddish"},
            {"vmw-MZ", "Emakhuwa"},
            {"en-AU", "English (Australia)"},
            {"en-CA", "English (Canada)"},
            {"en-IN", "English (India)"},
            {"en-IE", "English (Ireland)"},
            {"en-NZ", "English (New Zealand)"},
            {"en-SG", "English (Singapore)"},
            {"en-ZA", "English (South Africa)"},
            {"en-US", "English (USA)"},
            {"en-GB", "English (United Kingdom)"},
            {"eo-EU", "Esperanto"},
            {"et-EE", "Estonian"},
            {"ee-GH", "Ewe"},
            {"fn-FNG", "Fanagalo"},
            {"fo-FO", "Faroese"},
            {"fj-FJ", "Fijian"},
            {"fil-PH", "Filipino"},
            {"fi-FI", "Finnish"},
            {"fon-BJ", "Fon"},
            {"fr-BE", "French (Belgium)"},
            {"fr-CA", "French (Canada)"},
            {"fr-FR", "French (France)"},
            {"fr-CH", "French (Switzerland)"},
            {"fur-IT", "Friulian"},
            {"ff-FUL", "Fula"},
            {"gl-ES", "Galician"},
            {"grt-IN", "Garo"},
            {"ka-GE", "Georgian"},
            {"de-AT", "German (Austria)"},
            {"de-DE", "German (Germany)"},
            {"de-CH", "German (Switzerland)"},
            {"gil-KI", "Gilbertese"},
            {"glw-NG", "Glavda"},
            {"el-GR", "Greek"},
            {"gcl-GD", "Grenadian Creole English"},
            {"gn-PY", "Guarani"},
            {"gu-IN", "Gujarati"},
            {"gyn-GY", "Guyanese Creole English"},
            {"ht-HT", "Haitian Creole French"},
            {"khk-MN", "Halh Mongolian"},
            {"ha-NE", "Hausa"},
            {"haw-US", "Hawaiian"},
            {"he-IL", "Hebrew"},
            {"hig-NG", "Higi"},
            {"hil-PH", "Hiligaynon"},
            {"mrj-RU", "Hill Mari"},
            {"hi-IN", "Hindi"},
            {"hmn-CN", "Hmong"},
            {"hoc-IN", "Ho"},
            {"hu-HU", "Hungarian"},
            {"is-IS", "Icelandic"},
            {"ig-NG", "Igbo"},
            {"ilo-PH", "Ilocano"},
            {"id-ID", "Indonesian"},
            {"kl-GL", "Inuktitut Greenlandic"},
            {"ga-IE", "Irish Gaelic"},
            {"it-IT", "Italian (Italy)"},
            {"it-CH", "Italian (Switzerland)"},
            {"jam-JM", "Jamaican Creole English"},
            {"ja-JP", "Japanese"},
            {"jv-ID", "Javanese"},
            {"kac-MM", "Jingpho"},
            {"quc-GT", "K'iche'"},
            {"kbp-TG", "Kabiyè"},
            {"kea-CV", "Kabuverdianu"},
            {"kab-DZ", "Kabylian"},
            {"kln-KE", "Kalenjin"},
            {"kam-KE", "Kamba"},
            {"kjb-GT", "Kanjobal"},
            {"kn-IN", "Kannada"},
            {"kr-KAU", "Kanuri"},
            {"kar-MM", "Karen"},
            {"kas-IN", "Kashmiri (Arabic script)"},
            {"ks-IN", "Kashmiri (Devanagari script)"},
            {"kk-KZ", "Kazakh"},
            {"kha-IN", "Khasi"},
            {"km-KH", "Khmer"},
            {"ki-KE", "Kikuyu"},
            {"kmb-AO", "Kimbundu"},
            {"rw-RW", "Kinyarwanda"},
            {"rn-BI", "Kirundi"},
            {"guz-KE", "Kisii"},
            {"kg-CG", "Kongo"},
            {"kok-IN", "Konkani"},
            {"ko-KR", "Korean"},
            {"ckb-IQ", "Kurdish Sorani"},
            {"ky-KG", "Kyrgyz"},
            {"lo-LA", "Lao"},
            {"ltg-LV", "Latgalian"},
            {"la-XN", "Latin"},
            {"lv-LV", "Latvian"},
            {"lij-IT", "Ligurian"},
            {"li-NL", "Limburgish"},
            {"ln-LIN", "Lingala"},
            {"lt-LT", "Lithuanian"},
            {"lmo-IT", "Lombard"},
            {"lua-CD", "Luba-Kasai"},
            {"lg-UG", "Luganda"},
            {"luy-KE", "Luhya"},
            {"luo-KE", "Luo"},
            {"lb-LU", "Luxembourgish"},
            {"mas-KE", "Maa"},
            {"mk-MK", "Macedonian"},
            {"mag-IN", "Magahi"},
            {"mai-IN", "Maithili"},
            {"mg-MG", "Malagasy"},
            {"ms-MY", "Malay"},
            {"ml-IN", "Malayalam"},
            {"dv-MV", "Maldivian"},
            {"mfi-NG", "Malgwa"},
            {"mt-MT", "Maltese"},
            {"mam-GT", "Mam"},
            {"mni-IN", "Manipuri"},
            {"gv-IM", "Manx Gaelic"},
            {"mi-NZ", "Maori"},
            {"mr-IN", "Marathi"},
            {"mrt-NG", "Margi"},
            {"mhr-RU", "Mari"},
            {"mh-MH", "Marshallese"},
            {"men-SL", "Mende"},
            {"mer-KE", "Meru"},
            {"nyf-KE", "Mijikenda"},
            {"min-ID", "Minangkabau"},
            {"lus-IN", "Mizo"},
            {"mn-MN", "Mongolian"},
            {"sr-ME", "Montenegrin"},
            {"mfe-MU", "Morisyen"},
            {"mos-BF", "Mossi"},
            {"ndc-MZ", "Ndau"},
            {"ne-NP", "Nepali"},
            {"fuv-NG", "Nigerian Fulfulde"},
            {"niu-NU", "Niuean"},
            {"azj-AZ", "North Azerbaijani"},
            {"kmr-TR", "Northern Kurdish"},
            {"nd-ZW", "Northern Ndebele"},
            {"uzn-UZ", "Northern Uzbek"},
            {"nb-NO", "Norwegian Bokmål"},
            {"nn-NO", "Norwegian Nynorsk"},
            {"nus-SS", "Nuer"},
            {"ny-MW", "Nyanja"},
            {"oc-ES", "Occitan (Aran)"},
            {"oc-FR", "Occitan (France)"},
            {"or-IN", "Odia"},
            {"ory-IN", "Oriya"},
            {"pau-PW", "Palauan"},
            {"pi-IN", "Pali"},
            {"pag-PH", "Pangasinan"},
            {"pap-CW", "Papiamentu"},
            {"ps-PK", "Pashto"},
            {"fa-IR", "Persian"},
            {"pis-SB", "Pijin"},
            {"plt-MG", "Plateau Malagasy"},
            {"pl-PL", "Polish"},
            {"pt-BR", "Portuguese (Brazil)"},
            {"pt-PT", "Portuguese (Portugal)"},
            {"pot-US", "Potawatomi"},
            {"pa-IN", "Punjabi (India)"},
            {"pa-PK", "Punjabi (Pakistan)"},
            {"qu-PE", "Quechua"},
            {"rhg-MM", "Rohingya"},
            {"rhl-MM", "Rohingyalish"},
            {"ro-RO", "Romanian"},
            {"roh-CH", "Romansh"},
            {"run-BI", "Rundi"},
            {"ru-RU", "Russian"},
            {"acf-LC", "Saint Lucian Creole French"},
            {"sm-WS", "Samoan"},
            {"sg-CF", "Sango"},
            {"sa-IN", "Sanskrit"},
            {"sat-IN", "Santali"},
            {"sc-IT", "Sardinian"},
            {"gd-GB", "Scots Gaelic"},
            {"seh-ZW", "Sena"},
            {"sr-Cyrl-RS", "Serbian (Cyrillic script)"},
            {"sr-Latn-RS", "Serbian (Latin script)"},
            {"crs-SC", "Seselwa Creole French"},
            {"nso-ZA", "Sesotho"},
            {"shn-MM", "Shan"},
            {"sn-ZW", "Shona"},
            {"scn-IT", "Sicilian"},
            {"szl-PL", "Silesian"},
            {"sd-PK", "Sindhi"},
            {"si-LK", "Sinhala"},
            {"sk-SK", "Slovak"},
            {"sl-SI", "Slovenian"},
            {"so-SO", "Somali"},
            {"st-LS", "Sotho Southern"},
            {"azb-AZ", "South Azerbaijani"},
            {"nr-ZA", "Southern Ndebele"},
            {"pbt-PK", "Southern Pashto"},
            {"dik-SS", "Southwestern Dinka"},
            {"es-AR", "Spanish (Argentina)"},
            {"es-CO", "Spanish (Colombia)"},
            {"es-419", "Spanish (Latin America)"},
            {"es-MX", "Spanish (Mexico)"},
            {"es-ES", "Spanish (Spain)"},
            {"es-US", "Spanish (USA)"},
            {"srn-SR", "Sranan Tongo"},
            {"lvs-LV", "Standard Latvian"},
            {"zsm-MY", "Standard Malay"},
            {"su-ID", "Sundanese"},
            {"sw-KE", "Swahili"},
            {"ss-SZ", "Swati"},
            {"sv-SE", "Swedish"},
            {"syc-TR", "Syriac (Aramaic)"},
            {"tl-PH", "Tagalog"},
            {"ty-PF", "Tahitian"},
            {"tg-TJ", "Tajik"},
            {"tmh-DZ", "Tamashek (Tuareg)"},
            {"taq-ML", "Tamasheq"},
            {"ta-IN", "Tamil (India)"},
            {"ta-LK", "Tamil (Sri Lanka)"},
            {"trv-TW", "Taroko"},
            {"tt-RU", "Tatar"},
            {"te-IN", "Telugu"},
            {"tet-TL", "Tetum"},
            {"th-TH", "Thai"},
            {"bo-CN", "Tibetan"},
            {"ti-ET", "Tigrinya"},
            {"tpi-PG", "Tok Pisin"},
            {"tkl-TK", "Tokelauan"},
            {"to-TO", "Tongan"},
            {"als-AL", "Tosk Albanian"},
            {"ts-ZA", "Tsonga"},
            {"tsc-MZ", "Tswa"},
            {"tn-BW", "Tswana (Botswana)"},
            {"tn-ZA", "Tswana (South Africa)"},
            {"tum-MW", "Tumbuka"},
            {"tr-TR", "Turkish"},
            {"tk-TM", "Turkmen"},
            {"tvl-TV", "Tuvaluan"},
            {"tw-GH", "Twi"},
            {"udm-RU", "Udmurt"},
            {"uk-UA", "Ukrainian"},
            {"ppk-ID", "Uma"},
            {"umb-AO", "Umbundu"},
            {"ur-PK", "Urdu"},
            {"ug-CN", "Uyghur"},
            {"uz-UZ", "Uzbek"},
            {"vec-IT", "Venetian"},
            {"vi-VN", "Vietnamese"},
            {"svc-VC", "Vincentian Creole English"},
            {"vic-US", "Virgin Islands Creole English"},
            {"wls-WF", "Wallisian"},
            {"mfi-CM", "Wandala"},
            {"war-PH", "Waray"},
            {"cy-GB", "Welsh"},
            {"gaz-ET", "West Central Oromo"},
            {"wo-SN", "Wolof"},
            {"xh-ZA", "Xhosa"},
            {"yi-YD", "Yiddish"},
            {"yo-NG", "Yoruba"},
            {"zu-ZA", "Zulu"},
        };
    }
}
